<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProdukSeeder extends Seeder
{
    public function run()
    {
        $data = array(
            [
                'title' => 'Espresso',
                'cover' => 'espresso.jpg',
                'price' => '11000',
                'stock' => '8',
                'description' => 'Kopi yang dihasilkan dari proses penyeduhan kopi dengan tekanan dan suhu tinggi',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Americano',
                'cover' => 'americano.jpg',
                'price' => '15000',
                'stock' => '6',
                'description' => 'Kopi espreso yang dicampur dengan air panas',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe Milk',
                'cover' => 'CoffeMilk.jpg',
                'price' => '20000',
                'stock' => '20',
                'description' => 'Kopi yang manis dibuat dengan kopi dan susu yang dicampur',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Blue lagoon americano',
                'cover' => 'blue lagoon americano.jpg',
                'price' => '18000',
                'stock' => '15',
                'description' => 'Blue Lagoon Americano adalah minuman yang memukau dengan kelezatan yang menyegarkan dan citarasa yang mendalam. Dibuat dari perpaduan sempurna antara vodka, blue curaçao, dan campuran air soda, minuman ini menyajikan kesegaran yang tak tertandingi.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Caramel americano',
                'cover' => 'caramel americano.jpg',
                'price' => '20000',
                'stock' => '18',
                'description' => 'Caramel Americano adalah perpaduan yang memikat antara kekuatan kopi yang khas dengan sentuhan manis dan karamel yang lembut. Saat Anda pertama kali mencium aroma kopi segar yang menggoda dari cangkir Anda, Anda akan segera merasakan kehangatan dan keharuman yang mengundang.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe late aren',
                'cover' => 'coffe late aren.jpg',
                'price' => '18000',
                'stock' => '10',
                'description' => 'Cafe Latte Aren menggabungkan kelezatan tradisional kopi latte dengan sentuhan manis alami dari sirup aren, menciptakan pengalaman minum kopi yang menggoda dan memikat.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe late avocado',
                'cover' => 'coffe late avocado.jpg',
                'price' => '20000',
                'stock' => '17',
                'description' => 'Cafe Latte Avocado adalah kombinasi unik antara kopi yang kaya dan lembut dengan kelezatan alami dari buah alpukat yang lembut dan krimi.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe late caramel',
                'cover' => 'Ccoffe late caramel.jpg',
                'price' => '18000',
                'stock' => '15',
                'description' => '
                Cafe Latte Caramel adalah perpaduan sempurna antara kopi yang kaya dan susu yang lembut dengan sentuhan manis dari karamel yang lembut dan memikat.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe late havana',
                'cover' => 'coffe late havana.jpg',
                'price' => '15000',
                'stock' => '17',
                'description' => 'Cafe Latte Havana menghadirkan pengalaman minum kopi yang eksotis dengan sentuhan khas dari rum Havana yang hangat dan beraroma. Dari sekilas, aroma kopi yang harum akan memikat indera penciuman Anda, membangkitkan selera dengan kelezatan yang menggoda.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe late mochacino',
                'cover' => 'coffe late mochacino.jpg',
                'price' => '15000',
                'stock' => '16',
                'description' => 'Coffe latte mochaccino adalah perpaduan yang menggoda antara kopi espresso yang kaya dengan susu hangat yang lembut, diberi sentuhan tambahan cokelat yang menyenangkan.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe late tiramizu',
                'cover' => 'coffe late tiramizu.jpg',
                'price' => '18000',
                'stock' => '15',
                'description' => 'Coffe latte tiramisu adalah kombinasi yang menggoda antara kopi espresso yang kuat dan lembut dengan susu yang creamy, dilengkapi dengan sentuhan rasa tiramisu yang khas.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe late vanilla',
                'cover' => 'coffe late vanilla.jpg',
                'price' => '17000',
                'stock' => '18',
                'description' => 'Coffe latte vanilla adalah minuman yang menggugah selera dengan kombinasi sempurna antara kopi espresso yang kuat dan lembut dengan aroma manis dan harum vanila yang menyenangkan.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Coffe latte',
                'cover' => 'coffe late.jpg',
                'price' => '14000',
                'stock' => '15',
                'description' => 'Coffe latte adalah minuman kopi klasik yang terdiri dari kopi espresso yang kuat dan susu hangat yang lembut.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Havana americano',
                'cover' => 'havana americano.jpg',
                'price' => '20000',
                'stock' => '20',
                'description' => 'Havana Americano adalah variasi yang menarik dari minuman kopi klasik. Ini menggabungkan kekuatan kopi espresso dengan sentuhan unik dari rum Havana, menciptakan pengalaman minum kopi yang berani dan berbeda.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Long black',
                'cover' => 'long black.jpg',
                'price' => '12000',
                'stock' => '17',
                'description' => 'Long black adalah minuman kopi yang sederhana namun klasik, terdiri dari dua shot espresso yang diseduh di atas air panas.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Mango americano',
                'cover' => 'mango americano.jpg',
                'price' => '18000',
                'stock' => '17',
                'description' => 'Mango Americano adalah variasi yang segar dan berbeda dari minuman kopi klasik. Ini menggabungkan kekuatan kopi espresso dengan sentuhan buah mangga yang menyegarkan.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Melon americano',
                'cover' => 'melon americano.jpg',
                'price' => '15000',
                'stock' => '15',
                'description' => 'Melon Americano adalah variasi yang menarik dari minuman kopi klasik. Ini menggabungkan kekuatan kopi espresso dengan sentuhan segar dari buah melon.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Pandan americano',
                'cover' => 'padan americano.jpg',
                'price' => '15000',
                'stock' => '20',
                'description' => 'Pandan Americano adalah inovasi yang menggabungkan rasa unik dan eksotis dari daun pandan dengan kekuatan kopi espresso.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Pappermint americano',
                'cover' => 'pappermint americano.jpg',
                'price' => '18000',
                'stock' => '20',
                'description' => 'Peppermint Americano adalah kreasi yang menyegarkan dari minuman kopi klasik. Minuman ini menggabungkan kekuatan kopi espresso dengan sentuhan menyegarkan dari ekstrak peppermint atau sirup peppermint.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Sanger',
                'cover' => 'sanger.jpg',
                'price' => '13000',
                'stock' => '20',
                'description' => 'Rasanya segar dan sedikit asam dari buah jeruk, dengan sentuhan manis dari anggur merah dan kelezatan dari soda.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Strawberry americano',
                'cover' => 'strawberry americano.jpg',
                'price' => '15000',
                'stock' => '20',
                'description' => 'Strawberry Americano adalah inovasi yang segar dari minuman kopi klasik. Ini menggabungkan kekuatan kopi espresso dengan rasa manis dan segar dari stroberi.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Vanilla americano',
                'cover' => 'vanilla americano.jpg',
                'price' => '17000',
                'stock' => '20',
                'description' => 'Vanilla Americano adalah varian yang lezat dari minuman kopi klasik yang memadukan kekuatan espresso dengan rasa manis dan harum vanilla.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Wild rosa americano',
                'cover' => 'wild rosa americano.jpg',
                'price' => '15000',
                'stock' => '20',
                'description' => 'Wild Rosa Americano adalah inovasi yang menarik dari minuman kopi klasik, menggabungkan kekuatan espresso dengan sentuhan buah-buahan segar, terutama mawar liar.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Bihun goreng babi',
                'cover' => 'bihun goreng babi.jpg',
                'price' => '25000',
                'stock' => '20',
                'description' => 'Bihun goreng babi adalah hidangan khas Asia yang terdiri dari bihun yang digoreng bersama dengan daging babi dan berbagai bumbu serta bahan tambahan lainnya.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Bihun goreng seafood',
                'cover' => 'bihun goreng seafood.jpg',
                'price' => '28000',
                'stock' => '20',
                'description' => 'Hidangan ini terdiri dari bihun yang digoreng bersama dengan campuran seafood, seperti udang, cumi-cumi, dan kerang, serta berbagai sayuran seperti wortel, kubis, dan bawang bombay.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Bihun goreng telor',
                'cover' => 'bihun goreng telor.jpg',
                'price' => '20000',
                'stock' => '20',
                'description' => 'Bihun goreng telur adalah hidangan yang memikat dengan kombinasi lembut dan gurih dari bihun yang lembut, telur yang dicampur dengan indah, dan sentuhan harum dari rempah-rempah yang terbaik.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Ifumie goreng babi',
                'cover' => 'ifumie goreng babi.jpg',
                'price' => '25000',
                'stock' => '20',
                'description' => 'Ifumie goreng babi adalah hidangan yang lezat dan menggugah selera dari masakan Asia. Ifumie adalah mie kuning tipis yang digoreng hingga renyah dan kemudian disajikan bersama dengan daging babi yang dipotong kecil-kecil, sayuran segar seperti sawi, wortel, dan bawang bombay, serta bumbu-bumbu seperti kecap manis, kecap asin, bawang putih, bawang merah, dan cabai untuk memberikan cita rasa yang kaya dan beragam.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Ifumie goreng seafood',
                'cover' => 'ifumie goreng seafood.jpg',
                'price' => '25000',
                'stock' => '20',
                'description' => 'Ifumie goreng seafood adalah hidangan yang menggugah selera, terdiri dari mie kuning yang digoreng hingga renyah, dicampur dengan campuran seafood segar seperti udang, cumi-cumi, dan kerang.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Ifumie goreng telor',
                'cover' => 'ifumie goreng telor.jpg',
                'price' => '25000',
                'stock' => '20',
                'description' => 'fumie goreng telur adalah hidangan yang lezat dan memikat yang terdiri dari mie kuning yang digoreng hingga renyah, dicampur dengan telur yang telah dikocok dengan indah.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Indomie telor sosis',
                'cover' => 'indomie telor sosis.jpg',
                'price' => '18000',
                'stock' => '20',
                'description' => 'Hidangan ini terdiri dari mie Instan Indomie yang dimasak dan dicampur dengan telur yang telah dikocok dan sosis yang dipotong-potong.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Indomie telor',
                'cover' => 'indomie telor.jpg',
                'price' => '12000',
                'stock' => '20',
                'description' => 'Indomie telor adalah hidangan yang sangat populer di Indonesia, terutama di kalangan anak muda dan pecinta mie Instan. Ini adalah versi Indomie yang disajikan dengan tambahan telur.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Kwetiaw goreng babi',
                'cover' => 'kwetiaw goreng babi.jpg',
                'price' => '25000',
                'stock' => '20',
                'description' => 'Kwetiaw, yang merupakan jenis mie tipis yang terbuat dari beras, dimasak bersama dengan daging babi yang telah diiris tipis, sayuran seperti kubis, wortel, dan tauge, serta bumbu-bumbu seperti kecap manis, kecap asin, bawang putih, bawang merah, cabai, dan rempah-rempah lainnya.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Kwetiaw goreng seafood',
                'cover' => 'kwetiaw goreng seafood.jpg',
                'price' => '18000',
                'stock' => '20',
                'description' => 'Kwetiaw goreng seafood adalah hidangan lezat yang terdiri dari kwetiaw yang digoreng bersama dengan campuran seafood segar.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Kwetiaw goreng telor',
                'cover' => 'kwetiaw goreng telor.jpg',
                'price' => '15000',
                'stock' => '20',
                'description' => 'Kwetiaw goreng telor adalah hidangan yang menggugah selera terdiri dari kwetiaw yang digoreng bersama dengan telur.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Mie kuning goreng babi',
                'cover' => 'mie kuning goreng babi.jpg',
                'price' => '20000',
                'stock' => '20',
                'description' => 'Mie kuning goreng babi adalah sajian yang menggoda dengan berbagai cita rasa yang harmonis dan tekstur yang memikat.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Mie kuning goreng seafood',
                'cover' => 'mie kuning goreng seafood.jpg',
                'price' => '20000',
                'stock' => '20',
                'description' => 'Mie kuning goreng seafood adalah sebuah perpaduan luar biasa antara kelezatan mie kuning yang gurih dengan keanekaragaman rasa dan tekstur dari berbagai olahan seafood segar.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Mie kuning goreng telor',
                'cover' => 'mie kuning goreng telor.jpg',
                'price' => '15000',
                'stock' => '15',
                'description' => 'Mie kuning goreng telur adalah hidangan yang sederhana namun lezat, menggabungkan kegurihan mie kuning yang digoreng dengan sempurna dengan kelezatan telur yang dimasak dengan cara yang beragam.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Indomie Telur Rebus',
                'cover' => 'indomietelorrebus.jpg',
                'price' => '15000',
                'stock' => '20',
                'description' => 'Makanan yang dibuat untuk menemani nongkrong',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Indomie Telur Goreng',
                'cover' => 'indomietelorgoreng.jpg',
                'price' => '15000',
                'stock' => '20',
                'description' => 'Makanan yang dibuat untuk menemani nongkrong',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi goreng ayam',
                'cover' => 'nasi goreng ayam.jpg',
                'price' => '25000',
                'stock' => '18',
                'description' => 'Nasi goreng ayam adalah hidangan klasik yang tak pernah gagal menggugah selera. Dibuat dari nasi putih yang dimasak dan didinginkan sebelumnya, nasi goreng ayam memiliki tekstur yang lembut di dalam dan garing di luar setelah digoreng bersama bumbu-bumbu rempah yang khas.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi goreng babi',
                'cover' => 'nasi goreng babi.jpg',
                'price' => '25000',
                'stock' => '15',
                'description' => 'Nasi goreng babi adalah hidangan yang menggoda, memadukan kegurihan nasi yang digoreng dengan sempurna dengan cita rasa gurih dan lembut dari daging babi yang dimasak dengan berbagai cara. Daging babi yang telah dipotong kecil-kecil dan dimasak hingga renyah serta beraroma, kemudian dicampurkan dengan nasi goreng, memberikan tambahan kelezatan dan protein yang memuaskan.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi goreng kampung',
                'cover' => 'nasi goreng kampung.jpg',
                'price' => '22000',
                'stock' => '15',
                'description' => 'Nasi goreng kampung adalah hidangan yang merayakan kelezatan sederhana namun kaya dari masakan kampung tradisional. Dibuat dari nasi putih yang digoreng bersama dengan berbagai bahan tambahan yang menciptakan cita rasa yang autentik dan menggugah selera.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Nasi goreng seafood',
                'cover' => 'nasi goreng seafood.jpg',
                'price' => '20000',
                'stock' => '15',
                'description' => 'Nasi goreng seafood adalah sajian yang menggabungkan kekayaan rasa dari seafood segar dengan kelezatan nasi goreng yang gurih. Dibuat dengan nasi putih yang digoreng bersama dengan berbagai jenis seafood, hidangan ini menawarkan cita rasa laut yang autentik dan memikat.',
                'category' => 'Makanan',
            ],
            [
                'title' => 'Bandrek',
                'cover' => 'bandrek.jpg',
                'price' => '12000',
                'stock' => '20',
                'description' => 'Bandrek adalah minuman tradisional khas Indonesia yang memiliki kenikmatan yang unik dan menggoda. Di setiap tegukan, bandrek menghadirkan perpaduan hangatnya rempah-rempah dengan rasa manis yang memikat.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Bubble gum blue latte boba',
                'cover' => 'bubble gum blue latte boba.jpg',
                'price' => '15000',
                'stock' => '20',
                'description' => 'Bubble gum blue latte boba adalah inovasi yang menggabungkan beberapa elemen yang berbeda untuk menciptakan minuman yang unik dan menggoda. Minuman ini menggabungkan cita rasa bubble gum, kelembutan latte, dan kelezatan boba (atau bubble tea) dalam satu gelas yang menyegarkan dan memikat.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Green tea latte boba',
                'cover' => 'green tea latte boba.jpg',
                'price' => '15000',
                'stock' => '20',
                'description' => 'Green tea latte boba adalah perpaduan yang memikat antara kelembutan dan kelezatan. Dimulai dengan teh hijau yang kaya akan antioksidan dan aroma yang segar, minuman ini memberikan rasa yang menenangkan dan menyegarkan pada setiap tegukan.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Jus alpukat',
                'cover' => 'jus alpukat.jpg',
                'price' => '12000',
                'stock' => '15',
                'description' => 'Alpukat, dengan tekstur yang kental dan kaya akan nutrisi, memberikan dasar yang sempurna untuk minuman ini. Dengan rasa yang lembut dan krimi, alpukat memberikan kelembutan yang memanjakan lidah, sementara nutrisi yang kaya seperti lemak sehat dan serat membuatnya menjadi minuman yang bertenaga.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Jus buah naga',
                'cover' => 'jus buah naga.jpg',
                'price' => '15000',
                'stock' => '18',
                'description' => 'Jus buah naga adalah minuman yang segar dan menghidrasi yang terbuat dari buah naga, juga dikenal sebagai pitaya. Buah naga memiliki warna yang menarik dan rasa yang unik, sehingga jusnya sering menjadi favorit di kalangan pecinta jus dan minuman sehat.',
                'category' => 'Minuman',
            ],
            [
                'title' => 'Jus jeruk',
                'cover' => 'jus jeruk.jpg',
                'price' => '12000',
                'stock' => '17',
                'description' => 'Jeruk yang dipilih dengan baik memberikan jus dengan rasa yang segar dan manis, dengan sentuhan keasaman yang menyegarkan. Setiap tegukan memberikan ledakan citra yang menyegarkan, membuatnya menjadi minuman yang sempurna untuk dinikmati di pagi hari sebagai penyegar atau sebagai penawar dahaga di siang hari.',
                'category' => 'Minuman',
            ],
        );
        foreach ($data as $d) {
            Product::create([
                'title' => $d['title'],
                'cover' => $d['cover'],
                'price' => $d['price'],
                'stock' => $d['stock'],
                'description' => $d['description'],
                'category' => $d['category']
            ]);
        }
    }
}
